### ISSUE TITLE
Blog page

### ISSUE THREAD

**Issue by PervinHesenov105** [PervinHesenov105/JavaBoys#2]
Murad blog sehifesini yaz

1. Kenarda popular blog panelini de yaz
2. Blog basliqlarinda yazildigi tarix ay/il kimi gorsensin.
3. yazarin adi da gorsensin

**Comment by PervinHesenov105** [comment]
**Murad bunu task1 e push edersen.**

**Comment by Muradprfct** [comment]
Hell etdim.

**Comment by PervinHesenov105** [comment]
sagol.
